### ISSUE TITLE
render & window is not defined

### ISSUE THREAD

**Issue by michelwaechter** [kadiryazici/vite-ssr-vue3-example#2]
After pure git clone and yarn for installing dependencies: I just wanted to start with yarn dev, but got this errors and exit:

`TypeError: render is not a function
    at handleSsrRequest (/Users/michelwachter/src/farbien/vite-ssr-vue3-example/node_modules/vite-ssr/dev/server.js:100:37)
20:44:34 [vite] Internal server error: render is not a function
      at handleSsrRequest (/Users/michelwachter/src/farbien/vite-ssr-vue3-example/node_modules/vite-ssr/dev/server.js:100:37)
/node_modules/vite-ssr/vue/entry-client.js:26
    const url = window.location;
                ^

ReferenceError: window is not defined
    at Module.viteSSR (/node_modules/vite-ssr/vue/entry-client.js:26:17)
    at eval (/Users/michelwachter/src/farbien/vite-ssr-vue3-example/src/main.ts:21:54)
    at async instantiateModule (/Users/michelwachter/src/farbien/vite-ssr-vue3-example/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:56122:9)
error Command failed with exit code 1.`

What do i have to do?

**Comment by kadiryazici** [comment]
That is something with vite-ssr I guess, can you update all the dependencies to the latest version or exact version? It looks like vite-ssr is trying to run client script on server side.

**Comment by kadiryazici** [comment]
I should've left a lock file I guess.
